name: Test and Publish Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      BASE_URL: "https://api.restful-api.dev"  # Using Restful-API.dev for testing
      ENVIRONMENT: "test"
      REQUEST_TIMEOUT: "30"
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure-results
          
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
          
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v2
        with:
          path: allure-history
          
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v2 