name: Test and Publish Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      BASE_URL: "https://api.restful-api.dev"  # Using Restful-API.dev for testing
      ENVIRONMENT: "test"
      REQUEST_TIMEOUT: "30"
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure-results
          
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
          
      - name: Store Allure Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-history/
          retention-days: 30
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: always()
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        if: always()
        with:
          path: allure-history 