name: API Test Framework CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up Allure
      run: |
        curl -o allure-2.24.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
        sudo tar -zxvf allure-2.24.1.tgz -C /opt/
        sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
        allure --version
        
    - name: Check API Health
      run: |
        echo "Checking API health..."
        for i in {1..5}; do
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://api.restful-api.dev/objects)
          if [ "$HTTP_CODE" == "200" ]; then
            echo "API is healthy!"
            break
          fi
          if [ $i == 5 ]; then
            echo "API health check failed after 5 attempts"
            exit 1
          fi
          echo "Attempt $i failed with status $HTTP_CODE. Retrying in 10 seconds..."
          sleep 10
        done
        
    - name: Run tests
      env:
        BASE_URL: https://api.restful-api.dev/objects
      run: |
        # Run tests with retries for flaky tests
        pytest tests/ -v --alluredir=allure-results --reruns 3 --reruns-delay 5
        
    - name: Generate Allure Report
      if: always()  # Generate report even if tests fail
      run: |
        allure generate allure-results --clean -o allure-report
        
    - name: Upload Allure Report
      if: always()  # Upload report even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master' && always()  # Deploy even if tests fail
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report 
